- import_playbook: start_containers.yml

- name: Print some_fact from all hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Print group-specific some_fact
      debug:
        msg: "{{ some_fact }}"
